export const CHATS_ANDAMENTO_ADICIONAR = 'CHATS_ANDAMENTO_ADICIONAR';
export const CHATS_ANDAMENTO_REMOVER = 'CHATS_ANDAMENTO_REMOVER';
export const CHATS_ANDAMENTO_ATUALIZAR_CHAT = 'CHATS_ANDAMENTO_ATUALIZAR_CHAT';
