export const CHATS_AGUARDANDO_ADICIONAR = "CHATS_AGUARDANDO_ADICIONAR"
export const CHATS_AGUARDANDO_REMOVER = "CHATS_AGUARDANDO_REMOVER"
export const CHATS_AGUARDANDO_REMOVER_TODOS = "CHATS_AGUARDANDO_REMOVER_TODOS"
export const CHATS_AGUARDANDO_SET_SEGUNDOS_FILA = "CHATS_AGUARDANDO_SET_SEGUNDOS_FILA"
